export default {
    INTERNAL_SERVER_ERROR_CODE: 500,
    INTERNAL_SERVER_ERROR_MESSAGE: 'Internal Server Error',
    SUCCESS: 200,
    SUCCESS_MESSAGE: 'Success',
    ERROR_CODE: 412,
    ERROR_MESSAGE: 'Precondition Failed',
    BAD_REQUEST_CODE: 400,
    UNTHORIZED_CODE: 401,
    NEW_CREATED_CODE: 201,
    NEW_USER_MESSAGE: 'New User Has Been Created',
    NEW_CATEGORY_MESSAGE: 'New Category Has Been Created',
    NEW_PRODUCT_MESSAGE: 'New Product Has Been Created',
    USER_EXITS: 'Please Log IN',
    USER_NOT_EXITS: 'Please Sign Up',
    PASSWORD_WROGN: 'Please Check Your Password',
    CATEGORY_EXITS: 'Category Already Exits',
    PRODUCT_EXITS: 'Product Already Exits',
    CATEGORY_NOT_EXITS: 'Category Not Exits',
    PRODUCT_NOT_EXITS: 'Product Not Exits',
    CATEGORY_UPDATE: 'Category Has Been Updated',
    PRODUCT_UPDATE: 'Product Has Been Updated',
    CATEGORY_DELETE: 'Category Has Been Deleted',
    PRODUCT_DELETE: 'Product Has Been Deleted',
    CATEGORY_SINGLE: 'Single Category Has Been Find',
    PRODUCT_SINGLE: 'Single Product Has Been Find',
    CATEGORY_ALL: 'All Category Has Been Finded',
    PRODUCT_ALL: 'All Product Has Been Finded',
    TOKEN_NOT_PROVIDED: 'Token Not Found',
    TOKEN_UNTHORIZED: 'Token Not Valid',
    TOKEN_EXPIRE: 'Token Has Been Expire',
}